import numpy as np
z = np.eye(int(input("Кол-во столбцов: ")), int(input("Кол-во строк: ")))
x = np.eye(int(input("Кол-во столбцов: ")), int(input("Кол-во строк: ")))
c = np.eye(int(input("Тоже кол-во столбцов в z: ")), 1)
v = np.eye(int(input("Тоже кол-во столбцов в x: ")), 1)
q = np.column_stack((z, c[:, 0]))
w = np.column_stack((x, v[:, 0]))
print("1-ая матрица")
print(z)
print("2-ая матрица")
print(x)
print("1-ая матрица объеденная")
print(q)
print("2-ая матрица объеденная")
print(w)